name: list_operators

description: Operators and methods for Dart lists. The package uses null-safety features.

version: 0.0.1-nullsafety

homepage: https://github.com/simphotonics/list_operators

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  exception_templates: ^0.1.1-nullsafety
  lazy_memo: ^0.0.3-nullsafety

dev_dependencies:
  minimal_test: ^0.1.5-nullsafety
  pedantic: ^1.9.2
