name: list_operators

description: Extensions providing additional operators and methods for Dart lists. The package uses null-safety features.

version: 0.1.3-nullsafety

homepage: https://github.com/simphotonics/list_operators

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  exception_templates: ^0.2.0-nullsafety

dev_dependencies:
  minimal_test: ^2.0.1-nullsafety
  pedantic: ^1.9.2
