name: list_operators

description: Extensions providing vector-style operators and methods for Dart
  lists and iterables.

version: 0.5.0

homepage: https://github.com/simphotonics/list_operators

environment:
  sdk: '^3.0.0'

dependencies:
  exception_templates: ^0.3.1
  matcher: ^0.12.16+1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.5
