name: list_operators

description: Extensions providing additional operators and methods for Dart
  lists. The package uses null-safety features.

version: 0.2.0

homepage: https://github.com/simphotonics/list_operators

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  exception_templates: ^0.2.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.7
