name: list_operators

description: Extensions providing vector-style operators and methods for Dart lists.

version: 0.3.3

homepage: https://github.com/simphotonics/list_operators

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  exception_templates: ^0.2.4
  matcher: ^0.12.14

dev_dependencies:
  lints: ^2.0.1
  test: ^1.23.1
